//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWP_4IT_WP_VP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntersportEntities1 : DbContext
    {
        public IntersportEntities1()
            : base("name=IntersportEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<LastMonth> LastMonth { get; set; }
        public virtual DbSet<Requirements> Requirements { get; set; }
        public virtual DbSet<ThisMonth> ThisMonth { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
