//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWP_4IT_WP_VP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirements
    {
        public int id { get; set; }
        public string Product1 { get; set; }
        public string Product2 { get; set; }
        public string Product3 { get; set; }
        public string Product4 { get; set; }
        public string Product5 { get; set; }
        public string Product6 { get; set; }
        public string Product7 { get; set; }
    }
}
