//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWP_4IT_WP_VP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThisMonth
    {
        public int id { get; set; }
        public string name { get; set; }
        public string quantity { get; set; }
        public string measurement { get; set; }
        public string valuePerPiece { get; set; }
        public string valueTotal { get; set; }
        public string sum { get; set; }
    }
}
